
import type { ImagePlaceholder } from './placeholder-images';
import { PlaceHolderImages } from './placeholder-images';
import type { Offer, OfferTV, AddOn, CarouselSlide } from './definitions';

type NavLink = {
  href: string;
  label: string;
};

export const navLinks: NavLink[] = [
  { href: "/", label: "Beranda" },
  { href: "/reviews", label: "Ulasan" },
  { href: "/blog", label: "Blog"},
  { href: "/compare", label: "Bandingkan" },
  { href: "/register", label: "Daftar" },
  { href: "/cek-area", label: "Cek Area" },
  { href: "/hubungi-kami", label: "Hubungi Kami" },
  { href: "/personalized-offers", label: "Rekomendasi" },
  { href: "/speed-test", label: "Speed Test" },
];


export const offers: Offer[] = [
    {
        id: 'jet-20mbps',
        title: 'JET',
        speed: '20 Mbps',
        price: 'Rp 164.280/bln',
        promo: 'Promo Bayar 12 Bulan Gratis 3 Bulan',
        features: ['Setara Rp164rb-an/bulan', 'Internet Simetris 1:1', 'Unlimited Kuota', 'Tahan Cuaca Ekstrim'],
        image: {
            id: 'promo-12get3',
            description: 'Promo internet MyRepublic bayar 1 tahun gratis 3 bulan',
            imageUrl: 'https://picsum.photos/seed/promo12get3/800/600',
            imageHint: 'internet promo',
        },
    },
    {
        id: 'value',
        title: 'VALUE',
        speed: '30 Mbps',
        price: 'Rp 227.550/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Internet Simetris 1:1', 'Unlimited Kuota', 'Tahan Cuaca Ekstrim'],
        image: PlaceHolderImages.find(img => img.id === 'basic-connect')!,
    },
    {
        id: 'fast',
        title: 'FAST',
        speed: '50 Mbps',
        price: 'Rp 260.850/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Internet Stabil', 'Unlimited Kuota', '100% Full Fiber Optic'],
        image: PlaceHolderImages.find(img => img.id === 'family-stream')!,
    },
    {
        id: 'nova',
        title: 'NOVA',
        speed: '100 Mbps',
        price: 'Rp 333.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Cocok untuk streaming & kerja', 'Unlimited Kuota', 'Kecepatan Simetris'],
        image: PlaceHolderImages.find(img => img.id === 'hero-bg')!,
    },
    {
        id: 'mygamer',
        title: 'MYGAMER',
        speed: '250 Mbps',
        price: 'Rp 444.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Latensi Terendah untuk Gaming', 'Prioritas Jaringan Game', 'Internet Super Cepat'],
        image: PlaceHolderImages.find(img => img.id === 'gamer-pro')!,
    },
    {
        id: 'prime',
        title: 'PRIME',
        speed: '500 Mbps',
        price: 'Rp 555.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Kecepatan Maksimal', 'Untuk Kebutuhan Profesional', 'Performa Terbaik'],
        image: PlaceHolderImages.find(img => img.id === 'blog-1')!,
    },
];

export const offersTV: OfferTV[] = [
    {
        id: 'jet-20mbps-tv',
        title: 'JET',
        speed: '20 Mbps',
        price: 'Rp 239.760/bln',
        promo: 'Promo Bayar 12 Bulan Gratis 3 Bulan',
        features: ['Setara Rp239rb-an/bulan', 'Gratis Vidio Platinum & Genflix', 'Internet UNLIMITED', 'Tahan Cuaca'],
        image: {
            id: 'promo-12get3-tv',
            description: 'Promo internet dan TV MyRepublic bayar 1 tahun gratis 3 bulan',
            imageUrl: 'https://picsum.photos/seed/promo12get3tv/800/600',
            imageHint: 'tv promo',
        },
        channels: '76 Channel',
        stb: 'Termasuk STB Android 12',
    },
    {
        id: 'value-tv',
        title: 'VALUE',
        speed: '30 Mbps',
        price: 'Rp 320.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Vidio Platinum FREE 12 BULAN', 'Genflix FREE 12 BULAN', 'Internet UNLIMITED', 'Include ONT/Modem', 'Gratis Instalasi Rp500,000', 'Ideal untuk 1 - 3 Device', 'DL & UL 1:1 up to 30 Mbps'],
        image: PlaceHolderImages.find(img => img.id === 'basic-connect')!,
        channels: '65 Channel',
        stb: 'Termasuk STB Android 12',
    },
    {
        id: 'fast-tv',
        title: 'FAST',
        speed: '50 Mbps',
        price: 'Rp 335.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Vidio Platinum FREE 12 BULAN', 'Genflix FREE 12 BULAN', 'Internet UNLIMITED', 'Include ONT/Modem', 'Gratis Instalasi Rp500,000', 'Ideal untuk 1 - 5 Device', 'DL & UL 1:1 up to 50 Mbps'],
        image: PlaceHolderImages.find(img => img.id === 'family-stream')!,
        channels: '76 Channel',
        stb: 'Termasuk STB Android 12',
    },
    {
        id: 'nova-tv',
        title: 'NOVA',
        speed: '100 Mbps',
        price: 'Rp 385.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Vidio Platinum FREE 12 BULAN', 'Genflix FREE 12 BULAN', 'Internet UNLIMITED', 'Include ONT/Modem', 'Gratis Instalasi Rp500,000', 'Ideal untuk 1 - 7 Device', 'DL & UL 1:1 up to 100 Mbps'],
        image: PlaceHolderImages.find(img => img.id === 'hero-bg')!,
        channels: '76 Channel',
        stb: 'Termasuk STB Android 12',
    },
    {
        id: 'mygamer-tv',
        title: 'MYGAMER',
        speed: '250 Mbps',
        price: 'Rp 485.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Vidio Platinum FREE 12 BULAN', 'Genflix FREE 12 BULAN', 'Internet UNLIMITED', 'Include ONT/Modem', 'IP Public Static', 'Gratis Instalasi Rp500,000', 'DL & UL 1:1 up to 250 Mbps', 'Ideal untuk 1 - 10 Device', 'Akses langsung ke server game'],
        image: PlaceHolderImages.find(img => img.id === 'gamer-pro')!,
        channels: '76 Channel',
        stb: 'Termasuk STB ANDROID 12',
    },
    {
        id: 'prime-tv',
        title: 'PRIME',
        speed: '500 Mbps',
        price: 'Rp 585.000/bln',
        promo: 'Promo Bayar 5/9/12 Bulan Gratis s/d 6 Bulan',
        features: ['Vidio Platinum FREE 12 BULAN', 'Genflix FREE 12 BULAN', 'Internet UNLIMITED', 'Include ONT/Modem', 'Gratis Instalasi Rp500,000', 'DL & UL 1:1 up to 500 Mbps', 'Ideal untuk 1 - 15 Device'],
        image: PlaceHolderImages.find(img => img.id === 'blog-1')!,
        channels: '76 Channel',
        stb: 'Termasuk STB ANDROID 12',
    },
];

export const addOns: AddOn[] = [
  // Perangkat
  { id: "addon-router-plus", category: "perangkat", title: "Router Plus", description: "Wi-Fi single band 2,4 GHz", price: "Rp 13.636 / Bulan" },
  { id: "addon-ip-static", category: "perangkat", title: "IP Public Static V4", description: "Akses perangkat dari manapun", price: "Rp 25.000 / Bulan" },
  { id: "addon-router-pro", category: "perangkat", title: "Router Pro", description: "Wi-Fi dual band 2,4 dan 5 GHz", price: "Rp 40.000 / Bulan" },
  { id: "addon-wifi-mesh", category: "perangkat", title: "Wifi Mesh", description: "Dua Wi-Fi Router yang terhubung secara nirkabel", price: "Rp 80.000 / Bulan" },
  // TV
  { id: "addon-tv-entertainment", category: "tv", title: "TV Entertainment", price: "Rp 15.000 / Bulan", notes: "Termasuk paket Value30 keatas", features: ["Lifetime", "Rock Entertainment", "Rock Action"] },
  { id: "addon-tv-knowledge", category: "tv", title: "TV Knowledge & Lifestyle", price: "Rp 15.000 / Bulan", notes: "Termasuk paket Value30 keatas", features: ["afn", "BBC Lifestyle", "HGTV", "History", "Love Nature 4K"] },
  { id: "addon-tv-movies", category: "tv", title: "TV Movies", price: "Rp 20.000 / Bulan", notes: "Termasuk paket FAST50 keatas", features: ["Galaxy Premium", "IMC", "Zeebioskop"] },
  // Smart Home
  { id: "addon-sh-lite", category: "smart-home", title: "Smart Security Lite Plus", description: "Perangkat yang didapatkan:\n1x Indoor CCTV IP PTZ X Rabit\n1x SD Card 64Gb", price: "Rp 335.000", oldPrice: "Rp 385.765", discount: "-14%", features: ["AI Auto Tracking", "Image Sensor: 1/2.9″ Color CMOS", "Lens Type: FHD, 2MP", "Viewing Angle: 105°", "Nightvision: IR-Cut Autoswitch", "Video Resolution: 1920*1080", "Audio: Built-in Mic & Speaker", "Wi-Fi: IEEE 802.11 b/g/n 2.4GHz", "Cloud Storage: Support", "Terhubung dengan aplikasi Rabit"] },
  { id: "addon-sh-pro", category: "smart-home", title: "Smart Security Pro Plus", description: "Perangkat yang didapatkan:\n1x Indoor CCTV IP PTZ Screen Rabit\n1x SD Card 64Gb", price: "Rp 475.000", oldPrice: "Rp 538.918", discount: "-12%", features: ["AI Auto Tracking", "Image Sensor: 1/2.9″ Color CMOS", "Lens Type: FHD, 2MP", "Viewing Angle: 100°", "Nightvision: IR-Cut Autoswitch", "Video Resolution: 1920*1080", "Audio: Built-in Mic & Speaker", "Wi-Fi: IEEE 802.11 b/g/n 2.4GHz", "Cloud Storage: Support", "2 Way Video Call Screen", "Terhubung dengan aplikasi Rabit"] },
  { id: "addon-sh-starter", category: "smart-home", title: "Smart Home Starter Pack", description: "Perangkat yang didapatkan:\n1x Smart Light Bulb Color 10W Bluetooth\n1x Smart Plug 2 in 1 +Bluetooth Gateway\n1x Universal IR Remote Control (WiFi)", price: "Rp 245.000", oldPrice: "Rp 286.756", discount: "-15%", features: ["Smart Light Bulb: Color Temp: 2700K – 6500K", "Smart Light Bulb: Power 10 Watt", "Smart Plug: Power: 3680 W", "Smart Plug: Ampere: 16 A", "Smart Plug: Voltage: 230 V", "Universal IR Remote Control: WiFi: 802.11 b/g/n 2.4 Ghz", "Universal IR Remote Control: Jarak Infra Red: ≤ 8 Meter"] },
  // Speed Booster
  { id: "addon-speed-40", category: "speed-booster", title: "Speed Upgrade to 40Mbps", description: "Khusus Untuk Paket Value30", price: "Rp 10.000 / Bulan" },
  { id: "addon-speed-75", category: "speed-booster", title: "Speed Upgrade to 75Mbps", description: "Khusus Untuk Paket Fast50", price: "Rp 25.000 / Bulan" },
  { id: "addon-speed-150", category: "speed-booster", title: "Speed Upgrade to 150Mbps", description: "Khusus Untuk Paket Nova100", price: "Rp 45.000 / Bulan" },
  { id: "addon-speed-325", category: "speed-booster", title: "Speed Upgrade to 325Mbps", description: "Khusus Untuk Paket MyGamer250", price: "Rp 55.000 / Bulan" },
];

export const carouselSlides: CarouselSlide[] = [
    {
      id: 'hero-carousel-1',
      title: 'Rasakan Masa Depan Internet',
      description: 'Kecepatan super cepat, data tanpa batas, dan keandalan tak tertandingi. Bergabunglah dengan jaringan MyRepublic dan tingkatkan kehidupan digital Anda. GRATIS INSTALASI!',
      image: PlaceHolderImages.find(img => img.id === 'hero-carousel-1')!
    },
    {
      id: 'hero-carousel-2',
      title: 'Gaming Tanpa Kompromi',
      description: 'Latensi rendah dan jaringan prioritas untuk para gamer. Dominasi setiap pertandingan dengan paket MyGamer kami.',
      image: PlaceHolderImages.find(img => img.id === 'hero-carousel-2')!
    },
    {
      id: 'hero-carousel-3',
      title: 'Hiburan Tanpa Batas untuk Keluarga',
      description: 'Streaming film 4K dan nikmati tayangan TV favorit tanpa buffer. Paket combo TV kami hadir untuk hiburan keluarga terbaik.',
      image: PlaceHolderImages.find(img => img.id === 'hero-carousel-3')!
    }
  ];


type Faq = {
  question: string;
  answer: string;
};

export const faqs: Faq[] = [
  {
    question: "Apa itu MyRepublic?",
    answer: "MyRepublic adalah penyedia internet fiber optik yang menawarkan layanan broadband berkecepatan tinggi. Kami berdedikasi untuk menyediakan internet yang cepat, andal, dan terjangkau bagi penduduk Malang.",
  },
  {
    question: "Apa saja keuntungan internet fiber MyRepublic?",
    answer: "Jaringan fiber optik kami menyediakan kecepatan unggah dan unduh yang simetris, latensi lebih rendah, dan koneksi yang lebih stabil dibandingkan dengan internet kabel tradisional. Ini ideal untuk bermain game, streaming konten 4K, konferensi video, dan mendukung banyak perangkat yang terhubung.",
  },
  {
    question: "Bagaimana cara memeriksa jangkauan di area saya di Malang?",
    answer: "Anda dapat mengunjungi halaman 'Cek Area' kami untuk melihat daftar lengkap semua area yang telah tercover jaringan MyRepublic. Cukup cari nama kelurahan atau area Anda untuk memeriksa ketersediaan.",
  },
  {
    question: "Paket apa saja yang tersedia?",
    answer: "Kami menawarkan berbagai paket untuk memenuhi kebutuhan dan anggaran yang berbeda, dari paket Value kami untuk browsing sehari-hari hingga paket MyGamer kami untuk game online kompetitif. Anda dapat melihat penawaran unggulan kami di beranda.",
  },
  {
    question: "Bagaimana cara mendapatkan rekomendasi yang dipersonalisasi?",
    answer: "Gunakan halaman 'Rekomendasi' berbasis AI kami! Dengan memberikan alamat Anda dan menjelaskan penggunaan internet Anda, AI kami akan menyarankan paket terbaik yang disesuaikan khusus untuk Anda.",
  }
];

// Daftar topik blog yang disarankan
export const blogTopics = {
    "Teknologi": [
"Perkembangan Wi-Fi 7 dan Dampaknya bagi Pengguna Rumah",
"Perbedaan Wi-Fi 6 vs Wi-Fi 7: Mana yang Lebih Cocok?",
"Keunggulan Router Dual-Band untuk Rumah Modern",
"Tips Mengatasi Interferensi Wi-Fi di Apartemen",
"Manfaat Teknologi Mesh Wi-Fi untuk Rumah Bertingkat",
"Pengaruh Perangkat IoT terhadap Kinerja Wi-Fi",
"Teknologi Cloud Storage: Kelebihan dan Kekurangannya",
"AI Dalam Kehidupan Sehari-hari: Tren dan Prediksi",
"Cara Kerja Router Fiber Optik Modern",
"Perbedaan Modem, ONT, dan Router",
"Apakah Perlu Upgrade ke Internet Gigabit?",
"Teknologi Backhaul pada Mesh Wi-Fi dan Manfaatnya",
"Keamanan WPA3: Seberapa Aman?",
"Peran AI dalam Manajemen Jaringan Rumah",
"Teknologi Smart Home: Apa Saja yang Dibutuhkan?",
"Sensor IoT yang Paling Banyak Dipakai di Rumah Pintar",
"Teknologi Cloud Gaming: Masa Depan Gaming?",
"Cara Memilih Antena Router yang Tepat",
"Bandwidth vs Latency: Apa Bedanya?",
"Cara Meningkatkan Upload Speed untuk Kreator Konten",
"Perkembangan Fiber Optic di Indonesia",
"Tren Smart TV 2025",
"Router Wi-Fi Terbaik untuk Rumah Besar",
"Teknologi Kabel Bawah Laut Internet",
"Satellite Internet vs Fiber: Mana Lebih Baik?",
"Apa Itu Virtual Private Network (VPN)?",
"Tips Memilih Perangkat IoT yang Aman",
"Cara Kerja Sistem Internet di Smart City",
"AI untuk Memperkuat Keamanan Jaringan Rumah",
"Perbedaan IPv4 dan IPv6 untuk Pengguna Awam",
"Teknologi Edge Computing dan Penggunaannya",
"Chipset Wi-Fi di Smartphone: Apa Artinya?",
"Bagaimana Streaming 8K Bekerja?",
"Teknologi Anti-Hack pada Router Modern",
"Wireless Charging: Cara Kerja dan Kelemahannya",
"Perkembangan VR dan AR di Dunia Pendidikan",
"Teknologi Lidar: Cara Kerja dan Penerapannya",
"Upgrade Router vs Upgrade Paket Internet: Mana Lebih Penting?",
"Powerline Adapter: Solusi untuk Rumah Tebal",
"Kenapa Internet Malam Hari Lebih Cepat?",
"Masa Depan Jaringan Fiber Optik Indonesia",
"Internet untuk Smart Farming: Tren 2025",
"Teknologi Anti-Overheat pada Router Baru",
"Perkembangan AI dalam Dunia Medis",
"Perbedaan Kabel CAT5e, CAT6, dan CAT7",
"Apakah Perlu UPS untuk Router?",
"Teknologi Load Balancing Internet",
"Jaringan Multi-WAN: Solusi Internet Anti Putus",
"Trend Penggunaan AI di Perkantoran",
"Cara Memilih Mesh Wi-Fi untuk Rumah 3 Lantai",
"Router Gaming: Apa Bedanya dengan Router Biasa?",
"Smart City Indonesia: Menuju Transformasi Digital",
"Teknologi Cloud Backup untuk UMKM",
"AI dalam Pengembangan Software",
"Tren Kamera Smartphone 2025",
"Teknologi Charger GaN",
"Perkembangan Monitor 144Hz ke 360Hz",
"Keyboard Mechanical: Teknologi Switch",
"Teknologi Thermal Throttling di Laptop",
"Bluetooth 6: Apa yang Bisa Diharapkan?",
"Perbandingan Ethernet 1Gbps vs 2.5Gbps",
"Mesh Wi-Fi vs Repeater: Mana Lebih Baik?",
"Protokol Wi-Fi Terkini yang Perlu Kamu Ketahui",
"Router AX vs AC: Mana yang Harus Kamu Pilih?",
"Teknologi IoT untuk Rumah Minimalis",
"RFID vs NFC: Mana Lebih Aman?",
"Security Patch: Apa dan Mengapa Penting?",
"AI Chatbot dan Masa Depan Customer Service",
"Cloud Computing di Dunia Pendidikan",
"Teknologi OTT di Industri Hiburan",
"Router Outdoor: Solusi Internet Taman",
"Wi-Fi Boarding di Pesawat: Cara Kerjanya",
"Teknologi Modem 10G",
"AI Face Recognition dan Privasi",
"Quantum Computing: Pengaruhnya ke Dunia Internet",
"Perangkat Smart Home Murah vs Premium",
"Edge Router: Apa Itu dan Siapa yang Membutuhkannya?",
"Teknologi Multi-Gig Internet",
"Perkembangan Kecerdasan Buatan di 2026",
"Peran AI dalam Mengatur Konsumsi Listrik Rumah",
"Sensor IoT untuk Penghematan Energi",
"Koneksi Internet untuk Smart Apartment",
"Teknologi Auto-Channel pada Router",
"Beamforming Wi-Fi: Bagaimana Cara Kerja?",
"Router Open Source Firmware",
"Wi-Fi Analyzer: Cara Menggunakannya",
"Teknologi Switch Managed vs Unmanaged",
"Internet Dedicated vs Broadband: Mana Bedanya?",
"Firewall Rumah untuk Keamanan Maksimal",
"Teknologi IoT untuk Industri Retail",
"AI Vision: Kamera Cerdas Masa Kini",
"Teknologi Predictive Maintenance",
"Wi-Fi Sharing: Risiko dan Cara Menghindarinya",
"Perkembangan USB4 dan Thunderbolt",
"AP Enterprise: Perbedaan dengan AP Rumah",
"Hybrid Cloud dalam Bisnis Modern",
"Teknologi Encoding Video AV1",
"Socket Internet di Masa Depan",
"Automasi Rumah Tanpa Internet",
"Teknologi Anti Noise di Mikrofon Modern"
],
    "Gaming": [
"Game Online Paling Berat di Tahun 2025",
"Cara Mengatasi Packet Loss Ketika Bermain Game",
"Perbedaan Ping, Jitter, dan Packet Loss untuk Gamer",
"Game FPS yang Membutuhkan Latensi Rendah",
"MMORPG dengan Konsumsi Data Internet Tertinggi",
"Strategi Mengurangi Lag di Mobile Gaming",
"Router Gaming Terbaik Tahun Ini",
"Apa Itu Mode Game di Router?",
"Game Battle Royale Paling Populer 2025",
"Game E-Sport dengan Turnamen Terbesar",
"Cara Menstabilkan Koneksi Wi-Fi Saat Gaming",
"Game dengan Graphic Tercantik Tahun Ini",
"Game Casual Online untuk Mengisi Waktu",
"Tips Setting Grafik untuk Performa Maksimal",
"Game Horror Online Paling Seram",
"Perbedaan Gamer Casual dan Hardcore",
"Game MOBA Paling Kompetitif",
"Perbedaan Server Region dalam Game",
"Game Co-op Terbaik untuk Dimainkan Bersama Teman",
"Tips Membuat Streaming Game Lebih Stabil",
"Game Strategi Real-Time Terbaik",
"Game Open World Online Terluas",
"Game dengan Komunitas Terbesar",
"Tips Memilih Headset Gaming Murah Berkualitas",
"Monitor Terbaik untuk Gaming 2025",
"Keyboard Gaming: Memilih Switch yang Tepat",
"Mouse Gaming Wireless Terbaik",
"Game Fighting Online Paling Populer",
"Game Racing Online Tercepat",
"Tips Menghindari Cheater Online",
"VPN untuk Gaming: Perlukah?",
"Game yang Paling Boros Kuota",
"Game Multiplayer untuk Keluarga",
"Turnamen E-sports Terbesar Asia",
"Game Mobile Paling Populer 2025",
"Perkembangan E-sports di Indonesia",
"Game dengan Cross-Platform Support",
"Tips Upgrade PC untuk Gaming",
"Game Simulator Online Terbaik",
"Game Android Paling Berat 2025",
"Cloud Gaming: Masa Depan Dunia Game?",
"Koneksi Internet Ideal untuk Gaming",
"Game dengan Grafik Mirip Konsol",
"Setting Wi-Fi Terbaik untuk PS5",
"Game Co-op Lokal Online Terbaik",
"Karakter Game Paling Ikonik 2025",
"Game Sandbox Paling Kreatif",
"Sound System Terbaik untuk Gaming Room",
"Game Nostalgia Online yang Kembali Populer",
"Tips Menghindari Toxic Player",
"Tablet Terbaik untuk Gaming",
"Kontroler Game yang Paling Enak Digunakan",
"Game Sport Online untuk Pecinta Olahraga",
"Game RPG Online dengan Cerita Terbaik",
"Game Mobile Paling Ditunggu Tahun Ini",
"Tips Livestreaming Game Tanpa Lag",
"Game Browser Online Terbaik",
"Game PC Gratis Terbaik 2025",
"Game Online Genre FPS Terfavorit",
"Gadget yang Wajib Dimiliki Gamer",
"Game Anime Online yang Wajib Dicoba",
"Game Survival Online Terfavorit",
"Game Paling Ramai di Steam",
"Game Indie Online Terbaik",
"Game Roleplay Paling Unik",
"Game Perang Online Terpopuler",
"Game Casual Co-op Terbaik",
"Game Strategi dengan Komunitas Loyal",
"Game Online untuk Anak Aman & Edukatif",
"Game Musik Online Paling Seru",
"Build PC Gaming 10 Juta Terbaik",
"Build PC Gaming 20 Juta Terbaik",
"Tips Hemat Kuota Saat Main Game",
"Console War: PS5 vs Xbox vs Switch",
"Gadget Tambahan untuk Mobile Gamer",
"Game RPG Online Paling Variatif",
"MMO Sci-Fi Terbaik",
"Game Horror Co-op Online",
"Cloud Gaming: Kelebihan dan Kekurangan",
"Esport Lokal: Perkembangan di Kota Anda",
"Game Real-Time Strategy Paling Kompleks",
"Game Battle Royale Ter-ramai 2025",
"Aplikasi Booster Koneksi untuk Gamer",
"Game Paling Dinantikan 2026",
"Tips Membuat Ruang Streaming Gaming",
"Game Online Edukasi",
"Rekomendasi Wi-Fi untuk Gamer Apartemen",
"Game Online untuk Pasangan",
"Platform Gaming Cloud Terbaik",
"Game Sandbox Multiplayer Terpopuler",
"Game Asymmetric Online Terbaik",
"Game Shooter Taktis Paling Sulit",
"Game MOBA Paling Ramai 2025",
"Tips Meningkatkan FPS Tanpa Upgrade PC",
"Aplikasi Chat Gaming Terbaik",
"Steam Deck 2: Prediksi dan Spesifikasi",
"Game Free-to-Play dengan Grafis Terbaik",
"Game Online Paling Populer Sedunia 2025"
],
    "Hiburan": [
"Film 4K Terbaik untuk Penggemar Aksi",
"Drama Korea Terpopuler 2025",
"Anime Paling Ditunggu Tahun Ini",
"Rekomendasi Series Netflix untuk Keluarga",
"Film Indonesia Terbaik yang Wajib Ditonton",
"Tips Streaming Film Tanpa Buffering",
"Layanan Streaming Termurah di Indonesia",
"Perbandingan Netflix vs Disney+ vs Amazon Prime",
"Film Horor Terseram 2025",
"Rekomendasi Film Romantis untuk Pasangan",
"Film Komedi Terlucu Sepanjang Masa",
"Documentary Paling Inspiratif",
"Series Sci-Fi Terbaik di Platform Streaming",
"Film Superhero Terbaru 2025",
"Playlist Spotify untuk Kerja dari Rumah",
"Perkembangan Industri Film Digital",
"Tips Menghemat Kuota untuk Streaming",
"Film dengan Visual Terbaik",
"Konser Online Terpopuler",
"Perangkat Wajib untuk Penggemar Home Theater",
"Rekomendasi Soundbar Terbaik 2025",
"Proyektor Mini Terbaik untuk Hiburan",
"Game Party Seru untuk Ditonton di Stream",
"Podcast Indonesia Terpopuler",
"Karaoke Online: Aplikasi Terbaik",
"Video Editor untuk Konten Hiburan",
"Film Adaptasi Game yang Paling Sukses",
"Rekomendasi Acara TV Keluarga",
"Film Kartun Terbaik untuk Anak",
"Tips Memilih TV 4K Murah Berkualitas",
"Film Musik Terbaik Sepanjang Masa",
"Series Komedi untuk Menghilangkan Stres",
"Lensa Kamera Terbaik untuk Content Creator",
"Tips Membuat Konten Hiburan di YouTube",
"Film Thriller Paling Menegangkan",
"Drama Jepang Terbaik 2025",
"Acara Variety Show Korea Populer",
"Stand Up Comedy Spesial Terlucu",
"Film Dokumenter Teknologi Terbaik",
"Series Pendek Terfavorit",
"Film Olahraga Paling Inspiratif",
"Konser VR: Tren Baru Hiburan",
"Game Party untuk Keluarga di Rumah",
"Rekomendasi Speaker Bluetooth",
"Film Reboot Terbaik",
"Series Remake Paling Berhasil",
"Musik Elektronik Paling Hits 2025",
"Film Aksi Tanpa CGI Terbaik",
"Series Fantasi Dengan World Building Kuat",
"Film Tentang Kecerdasan Buatan",
"Acara Reality Show Paling Menghibur",
"Film Petualangan untuk Anak",
"Sinema Indonesia: Tren Digital 2025",
"Tips Menyusun Ruang Hiburan di Rumah",
"Baru Rilis: Film Terbaik Bulan Ini",
"Acara Game Show Populer",
"Film Detektif Terbaik",
"Film Animasi 3D Paling Memukau",
"Series Supernatural Paling Seru",
"Review Film Marvel Terbaru",
"TV QLED vs OLED: Mana Lebih Baik?",
"Aplikasi Streaming Musik Terbaik",
"Rekomendasi Film Silat Indonesia",
"Film Komedi untuk Nobar Bersama Teman",
"Film Survival Terpopuler",
"Musik Indie Indonesia Terfavorit",
"Top 10 Video TikTok Viral 2025",
"Series Kriminal Paling Seru",
"Film Misteri dengan Plot Twist Keren",
"Video Musik Terpopuler Tahun Ini",
"Tutorial Membuat Ruang Karaoke Rumahan",
"Tips Menonton Film Tanpa Spoiler",
"Series dengan Episode Pendek Terbaik",
"Film dengan Cinematography Terindah",
"TV 8K: Apakah Sudah Worth It?",
"Kompilasi OST Drama Terbaik",
"Platform Streaming Anime Terbaik",
"Film Sci-Fi Berdasarkan Novel",
"Series Asli Indonesia Terbaik",
"Film Terbaik Tentang Persahabatan",
"Acara Travel & Kuliner Terpopuler",
"Film Western Modern",
"Series Bertema Hacker",
"Acara Kompetisi Musik Terbaik",
"Home Theater Budget 5 Juta",
"Perbandingan Proyektor 1080p vs 4K",
"Film Black-and-White Terbaik",
"Acara Dokumenter Hewan Mengagumkan",
"Film Inspiratif Pengusaha Startup",
"Komposer Musik Film Terbaik",
"Playlist Musik Relaksasi 2025",
"Film Tonal Cooling Terbaik",
"Rekomendasi TV untuk Streaming",
"Series Terbaik Berdasarkan Rating IMDB",
"Film Live-Action Adaptasi Anime Terpopuler",
"Konten Creator Hiburan Paling Berpengaruh",
"Film Bertema Teknologi",
"Series Paling Banyak Ditonton Tahun Ini"
],
    "Gaya Hidup & Produktivitas": [
"Cara Meningkatkan Produktivitas saat WFH",
"Teknik Time Blocking untuk Produktivitas",
"Minimalisme Digital: Mengurangi Aplikasi Tidak Perlu",
"Tips Menjaga Kesehatan Mata saat Bekerja Online",
"Peran Internet Cepat dalam Pendidikan Modern",
"Tips Mengelola Data Keluarga Secara Aman",
"Work-Life Balance di Era Digital",
"Alat Smart Home Untuk Produktivitas",
"Teknik Deep Work untuk Fokus Maksimal",
"Aplikasi Manajemen Tugas Terbaik",
"Mindfulness untuk Pekerja Remote",
"Cara Menyimpan Data Keluarga dengan Aman",
"Tips Mengurangi Distraksi Saat Meeting Online",
"Alasan Internet Cepat Penting untuk UMKM",
"Platform Pembelajaran Online Terbaik",
"Tips Membuat Jadwal Belajar Anak",
"Peran Internet dalam Meningkatkan Karier",
"Tips Menjaga Keamanan Anak di Dunia Online",
"Digital Detox: Cara Memulai",
"Aplikasi Keuangan Pribadi Terbaik",
"Tips Membuat Workspace Nyaman di Rumah",
"Produktivitas Menggunakan AI Tools",
"Bagaimana Internet Membantu Freelancers",
"Aplikasi Kalender Terbaik 2025",
"Manajemen Waktu untuk Ibu Rumah Tangga",
"Cara Menghemat Kuota untuk Pelajar",
"Teknik Pomodoro untuk Pemula",
"Tips Menjaga Mood Saat Work From Home",
"Peran Teknologi dalam Bisnis Kuliner",
"Platform Cloud Storage Terbaik",
"Perangkat IoT untuk EFisiensi Rumah",
"Teknik Journaling Digital",
"Manfaat Smartwatch untuk Produktivitas",
"Tips Mengatur Notifikasi Digital",
"Teknologi untuk Self-Improvement",
"Manfaat Internet untuk Karyawan Remote",
"Alat Meeting Online Terbaik",
"Aplikasi Catatan Terbaik",
"Peran Wi-Fi Cepat untuk Keluarga",
"Teknik Mengurangi Stres dengan Aplikasi",
"Aplikasi Habit Tracker Terbaik",
"Teknologi Kebugaran Rumah",
"Smart Lamp untuk Kesehatan Tidur",
"Peran AI dalam Pendidikan Anak",
"Tips Memilih Laptop untuk Pekerja Remote",
"Tips Membuat Home Office Minimalis",
"Aplikasi untuk Belajar Skill Baru",
"Peran Internet dalam Kreativitas",
"Tips Mengatur Manajemen File Online",
"Cloud Storage untuk UMKM",
"Tips Membuat Konten Kerja yang Rapi",
"Teknologi untuk Orang Tua Modern",
"Tips Menjaga Keamanan Password",
"Cara Mengelola Screen Time Anak",
"Produktivitas Tanpa Gadget: Mungkin?",
"Podcast Terbaik untuk Produktivitas",
"Aplikasi Penjadwalan Tim",
"Teknik Focus Time untuk Pelajar",
"Aplikasi Membaca Buku Digital Terbaik",
"Tips Mengatur Perangkat untuk Anak",
"Manfaat Koneksi Internet Stabil",
"Tips Memilih Wi-Fi untuk Rumah",
"Gaya Hidup Digital Minimalis",
"Peran Internet dalam Self-Development",
"Tips Mengatur Data Cloud Secara Aman",
"Teknologi untuk Para Pelajar",
"Cara Mengatur Waktu Pekerjaan Freelance",
"Tips Mengatur Workspace untuk Pelajar",
"Aplikasi Pembayaran Digital Terpopuler",
"Manfaat Sensor IoT untuk Rumah",
"Tips Meningkatkan Disiplin Harian",
"Peran Teknologi Wearable untuk Kesehatan",
"Alasan Mengapa Backup Data Itu Penting",
"Tips Produktivitas untuk Orang Sibuk",
"Aplikasi Desain Gratis Terbaik",
"Tips Mengatur Aplikasi Sosial Media",
"Teknik Single Tasking",
"Produktivitas dengan Smartphone",
"Tips Mengurangi Distraksi Smartphone",
"Koneksi Internet untuk Keluarga Produktif",
"Tips Mengatur Manajemen Tugas Keluarga",
"Platform Belajar Coding untuk Pemula",
"Aplikasi Parenting Modern",
"Manfaat Wi-Fi Cepat untuk Rumah Cerdas",
"Teknologi untuk Kesehatan Keluarga",
"Tips Work From Cafe yang Efektif",
"Tren Gaya Hidup Digital 2025",
"Aplikasi Olahraga Online",
"Tips Mengatur Manajemen Tim Kerja Remote",
"Alasan Bisnis Butuh Website di Era Digital",
"Manfaat Video Call untuk Hubungan Jarak Jauh",
"Tips Mengurangi Notifikasi Tidak Penting",
"Teknologi Rumah Minimalis",
"Tips Belajar Online Lebih Efektif",
"Teknologi untuk Self-Care Digital",
"Manfaat Internet untuk Ibu Rumah Tangga",
"Tips Menjaga Keamanan Data Pribadi",
"Aplikasi Cloud Notes Terbaik",
"Teknologi untuk Produktivitas Kantor"
],
    "Lokal (Malang)": [
"Cafe di Malang dengan Wi-Fi Kencang untuk Nugas",
"Tempat Nongkrong Malang Paling Cozy",
"Coworking Space Terbaik di Malang",
"Komunitas Startup Teknologi Malang Paling Aktif",
"Perkembangan Infrastruktur Internet di Malang",
"Event Teknologi Besar di Malang Raya",
"UMKM Berbasis Digital Terbaik di Malang",
"Tempat Belajar Coding di Malang",
"Gamer Malang yang Berprestasi di Esports",
"Malang sebagai Kota Digital 2025",
"Jaringan Fiber Optik di Malang: Perkembangannya",
"Review Provider Internet Terbaik di Malang",
"Tempat Les Desain Grafis di Malang",
"Cafe Ramah Remote Worker",
"Area Perumahan di Malang dengan Internet Terbaik",
"Tips Cari Kost dengan Wi-Fi Cepat di Malang",
"Kegiatan Komunitas IT Malang",
"Startup EduTech Asal Malang",
"Pengusaha Muda Digital dari Malang",
"Perkembangan Gaming Center di Malang",
"Rental PC Gaming Terbaik",
"Toko Komputer Paling Lengkap di Malang",
"Tempat Nobar Sepak Bola di Malang",
"Event Esport Bulanan di Malang",
"Tempat Main PS5 di Malang",
"Malang Digital Conference 2025",
"Festival Teknologi Malang",
"Tempat Belajar Editing Video di Malang",
"Cafe Instagramable dengan Wi-Fi Kencang",
"Pengaruh Teknologi pada UMKM Malang",
"Event Komunitas Fotografi Malang",
"Tempat Gathering Komunitas Gamer",
"Workshop Coding for Kids di Malang",
"Malang Creative Movement",
"Startup Kuliner Digital Malang",
"Pengusaha Online Shop Sukses dari Malang",
"Kota Malang Menuju Smart City",
"Event Startup Pitching Malang",
"Sekolah IT Terbaik di Malang",
"Tempat Persewaan Peralatan Streaming",
"Pelatihan AI untuk Pelajar Malang",
"Layanan Internet Dedicated di Malang",
"Spot Wi-Fi Gratis di Alun-Alun Malang",
"Malang Tech Expo",
"Event Game Developer Lokal",
"Tempat Belajar Animasi di Malang",
"Jasa Internet UMKM Malang",
"Cafe dengan Stop Kontak Banyak",
"Kegiatan Komunitas Drone Malang",
"Komunitas Content Creator Malang",
"Event Kampus IT di Malang",
"Tempat Nobar Film Komunitas",
"Perkembangan Smart Home di Malang",
"Tempat Belanja Laptop Terbaik",
"Event Workshop Digital Marketing",
"Kelas Online Malang",
"Cafe Paling Nyaman untuk Freelancer",
"Tempat Nongkrong Gamer",
"Malang Esports Championship",
"Coding Bootcamp di Malang",
"Startup IoT dari Malang",
"Bisnis Warung Digital di Malang",
"Internet Fiber Tercepat di Malang",
"Perumahan dengan Infrastruktur Digital Bagus",
"Malang VR Experience",
"Galeri Seni Digital Malang",
"Teknologi Pertanian di Batu & Malang",
"Komunitas Robotik Malang",
"Event Review Gadget di Malang",
"Bisnis Internet Rumahan di Malang",
"Cafe Ramah Podcasting",
"Studio Rental Streaming",
"Event Teknologi Anak Muda Malang",
"Cafe 24 Jam dengan Internet Kencang",
"Komunitas Developer Game Horor",
"Startup Marketplace Lokal Malang",
"Workshop Web Developer",
"Tempat Sewa Kamera di Malang",
"Cafe Outdoor Wi-Fi Kencang",
"Perkembangan Digital Payment di Malang",
"Malang Super Fast Internet Program",
"Event Film Maker Malang",
"Tempat Belajar Fotografi Pemula",
"Workshop Desain UI/UX di Malang",
"Layanan Internet Korporat Malang",
"Event Startup Ecosystem Malang",
"Komunitas Laptop Enthusiast Malang",
"Event Computer Fair Malang",
"Event Music Tech Malang",
"Workshop Smart Home",
"Komunitas Gadget Reviewer",
"Startup Pendidikan Anak Malang",
"Bisnis Internet Cafe Modern",
"Cafe Hidden Gem dengan Wi-Fi Ngebut",
"Coworking Space Hemat Siswa",
"Event Perkembangan AI di Malang",
"Toko Smart Home Device Malang",
"Komunitas Tech Blogger Malang",
"Portal Informasi Teknologi Malang"
]
};
