// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.

import { FirebaseOptions } from 'firebase/app';

/**
 * The Firebase configuration object.
 *
 * This object is used to initialize the Firebase app.
 * It is automatically generated by Firebase Studio.
 *
 * **DO NOT EDIT THIS FILE MANUALLY.**
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};
