// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.

import { FirebaseOptions } from 'firebase/app';

/**
 * The Firebase configuration object.
 *
 * This object is used to initialize the Firebase app.
 * It is automatically generated by Firebase Studio.
 *
 * **DO NOT EDIT THIS FILE MANUALLY.**
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyBil_enAbfCC7jxpgBt3fyW57SfFAN662I",
  authDomain: "studio-7837155073-9a6c4.firebaseapp.com",
  projectId: "studio-7837155073-9a6c4",
  storageBucket: "studio-7837155073-9a6c4.appspot.com",
  messagingSenderId: "56562536434",
  appId: "1:56562536434:web:7968799a01698ed4c9256b",
};
